version: 2.1

orbs:
  python: circleci/python@3.0.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9-rc-node-browsers # With this image Chrome works fine, but the image is deprecated
    executor: python/default
#    parallelism: 2 # Parallel runs: https://circleci.com/docs/parallelism-faster-jobs/
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Python Dependencies and Upgrade pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run @priority_high scenarios
          command: |
            . venv/bin/activate
            behave --tags=priority_high
          when: always

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test