version: 2.1

orbs:
  python: circleci/python@3.0.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9-rc-node-browsers # With this image Chrome works fine, but the image is deprecated
    executor: python/default
    parallelism: 4 # Parallel runs: https://circleci.com/docs/parallelism-faster-jobs/
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Python Dependencies and Upgrade pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Install Allure Commandline
          command: |
            . venv/bin/activate
            npm install allure-commandline --save-dev
          when: always

#      - run:
#          name: Run @priority_high scenarios
#          command: |
#            . venv/bin/activate
#            behave --tags=priority_high --no-skipped
#          when: always
#
#      - run:
#          name: Run @priority_medium scenarios
#          command: |
#            . venv/bin/activate
#            behave --tags=priority_medium --no-skipped
#          when: always

      - run:
          name: Run @level_e2e scenarios
          command: |
            . venv/bin/activate
            behave --tags=level_e2e --no-skipped
          when: always

      - run:
          name: Generate Allure Report
          command: |
            ./node_modules/.bin/allure generate --single-file allure-results --clean -o allure-report
          when: always

      - store_artifacts:
          path: allure-report

      - store_artifacts:
          path: allure-screenshot

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test